export { default as BugIcon } from './Bug/Bug'
export { default as CommandIcon } from './Command/Command'
export { default as CrossIcon } from './Cross'
export { default as EmailIcon } from './Email'
export { default as FileIcon } from './File'
export { default as FolderIcon } from './Folder'
export { default as InfoIcon } from './Info'
export { default as MoonIcon } from './Moon'
export { default as PlusIcon } from './Plus'
export { default as SettingsIcon } from './Settings/Settings'
export { default as SpinIcon } from './Spin'
export { default as StopIcon } from './Stop'
export { default as SunIcon } from './Sun'
export { default as TelegramIcon } from './Telegram'
export { default as TickIcon } from './Tick'
export { default as WhatsappIcon } from './Whatsapp'

